# Generated by Django 3.1.1 on 2020-09-10 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appelation', models.CharField(max_length=50)),
                ('cru', models.CharField(max_length=50)),
                ('pays', models.CharField(max_length=50)),
                ('region', models.CharField(blank=True, max_length=50, null=True)),
                ('lieuAchat', models.CharField(blank=True, max_length=50, null=True)),
                ('prix', models.FloatField()),
                ('millesime', models.IntegerField()),
                ('cepage', models.CharField(max_length=100)),
                ('proprietaire', models.CharField(blank=True, max_length=50, null=True)),
                ('degre', models.FloatField()),
            ],
        ),
    ]
