# Generated by Django 3.1.1 on 2020-09-10 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('soirees', '0002_vin'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Vin',
        ),
    ]
